DROP TYPE TP_NT_FONE force;
DROP TYPE TP_POSICIONADORES force;
DROP TYPE TP_ATUADORES force;
DROP TYPE TP_VALVULAS force;
DROP TYPE TP_SENSORES force;
DROP TYPE TP_FLUXOINST force;
DROP TYPE TP_INSTRUMENTOS force;
DROP TYPE TP_FLUX_PROJ force;
DROP TYPE TP_FLUXOGRAMA force;
DROP TYPE TP_EXECUCAO force;
DROP TYPE TP_PROJETOS force;
DROP TYPE TP_PLANTA_INDUSTRIAL force;
DROP TYPE TP_PROJETISTA force;
DROP TYPE TP_INSTRUMENTISTA force;
DROP TYPE TP_SALARIO force;
DROP TYPE TP_FUNCIONARIO force;

CREATE OR REPLACE TYPE TP_NT_FONE AS TABLE OF VARCHAR2 (9);
/
CREATE OR REPLACE TYPE TP_FUNCIONARIO AS OBJECT(
CPF VARCHAR2(11),
NOME VARCHAR2(20),
SOBRENOME VARCHAR2(20),
IDADE NUMBER,
DATA_ENTRADA DATE,
TELEFONE TP_NT_FONE,		
REF_CHEFE REF TP_FUNCIONARIO
) NOT FINAL NOT INSTANTIABLE;
/


CREATE OR REPLACE TYPE TP_SALARIO AS OBJECT(
CPF VARCHAR2(11),
DATA_REAJUSTE DATE,
VALOR_SAL NUMBER,
MOEDA VARCHAR2(10),
REF_FUNCIONARIO REF TP_FUNCIONARIO
)FINAL;
/

CREATE OR REPLACE TYPE TP_INSTRUMENTISTA under TP_FUNCIONARIO(
TURNO VARCHAR2(9)
)FINAL;
/

CREATE OR REPLACE TYPE TP_PROJETISTA under TP_FUNCIONARIO(
ESPECIALIZACAO VARCHAR2(20),
FORMACAO_SUP VARCHAR2(20),
CREA VARCHAR2(15)
)FINAL;
/

CREATE OR REPLACE TYPE TP_PLANTA_INDUSTRIAL AS OBJECT(
TAG_PLANTA VARCHAR2(10),
INDUSTRIA VARCHAR2(20),
LOCALIZACAO VARCHAR2(20)
)FINAL;
/

CREATE OR REPLACE TYPE TP_PROJETOS AS OBJECT(
COD_PROJ VARCHAR2(15),
CLIENTE VARCHAR2(15),
DESCRICAO VARCHAR2(30)
)FINAL;
/

CREATE OR REPLACE TYPE TP_EXECUCAO AS OBJECT(
CPF VARCHAR2(11),
COD_PROJ VARCHAR2(15),
TAG_PLANTA VARCHAR2(10),
DATA_EXEC DATE,
REF_PROJETISTA REF TP_PROJETISTA,
REF_PROJETOS REF TP_PROJETOS,
REF_PLANTA_INDUSTRIAL REF TP_PLANTA_INDUSTRIAL
)FINAL;
/

CREATE OR REPLACE TYPE TP_FLUXOGRAMA AS OBJECT(
COD_FLUX VARCHAR2(15),
NUM_DOC VARCHAR2(15),
AREA VARCHAR2(15),
REF_PROJETISTA REF TP_PROJETISTA
)FINAL;
/

CREATE OR REPLACE TYPE TP_FLUX_PROJ AS OBJECT(
COD_FLUX VARCHAR2(15),
COD_PROJ VARCHAR2(15),
REF_FLUXOGRAMA REF TP_FLUXOGRAMA,
REF_PROJETOS REF TP_PROJETOS
)FINAL;
/

CREATE OR REPLACE TYPE TP_INSTRUMENTOS AS OBJECT(
TAG_INST VARCHAR2(10),
DATA_FAB DATE,
UNID_ENG VARCHAR2(5),
MIN_VAL NUMBER,
MAX_VAL NUMBER
)NOT FINAL NOT INSTANTIABLE;
/

CREATE OR REPLACE TYPE TP_FLUXOINST AS OBJECT(
COD_FLUX VARCHAR2(15),
TAG_INST VARCHAR2(10),
REF_FLUXOGRAMA REF TP_FLUXOGRAMA,
REF_INSTRUMENTOS ref TP_INSTRUMENTOS
)FINAL;
/

CREATE OR REPLACE TYPE TP_SENSORES under TP_INSTRUMENTOS(
FUNCAO VARCHAR2(15),
SINAL VARCHAR2(15),
SENSIBILIDADE NUMBER
)FINAL;
/

CREATE OR REPLACE TYPE TP_VALVULAS under TP_INSTRUMENTOS(
ESTRUTURA VARCHAR2(15),
DIAMETRO NUMBER,
VEDACAO VARCHAR2(15)
)FINAL;
/

CREATE OR REPLACE TYPE TP_ATUADORES under TP_INSTRUMENTOS(
DIAMETRO NUMBER,
EIXO VARCHAR2(10),
TAG_V VARCHAR2(10),
REF_VALVULAS REF TP_VALVULAS
)FINAL;
/

CREATE OR REPLACE TYPE TP_POSICIONADORES under TP_INSTRUMENTOS(
ACIONAMENTO VARCHAR2(15),
TEMPO_RESP NUMBER,
FUNC_DIAG VARCHAR2(4),
TAG_A VARCHAR2(10),
REF_ATUADORES REF TP_ATUADORES
)FINAL;
/